// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(larksync_ffiFFI)
    import larksync_ffiFFI
#endif

private extension RustBuffer {
    /// Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len: 0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_larksync_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    /// Frees the buffer in place.
    /// The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_larksync_ffi_rustbuffer_free(self, $0) }
    }
}

private extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

private extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

private func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

/// Reads an integer at the current offset, in big-endian order, and advances
/// the offset on success. Throws if reading the integer would move the
/// offset past the end of the buffer.
private func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset ..< reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value) { reader.data.copyBytes(to: $0, from: range) }
    reader.offset = range.upperBound
    return value.bigEndian
}

/// Reads an arbitrary number of bytes, to be used to read
/// raw bytes, this is useful when lifting strings
private func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> [UInt8] {
    let range = reader.offset ..< (reader.offset + count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer { buffer in
        reader.data.copyBytes(to: buffer, from: range)
    }
    reader.offset = range.upperBound
    return value
}

/// Reads a float at the current offset.
private func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return try Float(bitPattern: readInt(&reader))
}

/// Reads a float at the current offset.
private func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return try Double(bitPattern: readInt(&reader))
}

/// Indicates if the offset has reached the end of the buffer.
private func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

private func createWriter() -> [UInt8] {
    return []
}

private func writeBytes<S: Sequence>(_ writer: inout [UInt8], _ byteArr: S) where S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

/// Writes an integer in big-endian order.
///
/// Warning: make sure what you are trying to write
/// is in the correct type!
private func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

private func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

private func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

/// Protocol for types that transfer other types across the FFI. This is
/// analogous to the Rust trait of the same name.
private protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

/// Types conforming to `Primitive` pass themselves directly over the FFI.
private protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType {}

extension FfiConverterPrimitive {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

/// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
/// Used for complex types where it's hard to write a custom lift/lower.
private protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
        var writer = createWriter()
        write(value, into: &writer)
        return RustBuffer(bytes: writer)
    }
}

/// An error type for FFI errors. These errors occur at the UniFFI level, not
/// the library level.
private enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

private extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        lock()
        defer { self.unlock() }
        return try f()
    }
}

private let CALL_SUCCESS: Int8 = 0
private let CALL_ERROR: Int8 = 1
private let CALL_UNEXPECTED_ERROR: Int8 = 2
private let CALL_CANCELLED: Int8 = 3

private extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T
) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
    case CALL_SUCCESS:
        return

    case CALL_ERROR:
        if let errorHandler = errorHandler {
            throw try errorHandler(callStatus.errorBuf)
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.unexpectedRustCallError
        }

    case CALL_UNEXPECTED_ERROR:
        // When the rust code sees a panic, it tries to construct a RustBuffer
        // with the message.  But if that code panics, then it just sends back
        // an empty buffer.
        if callStatus.errorBuf.len > 0 {
            throw try UniffiInternalError.rustPanic(FfiConverterString.lift(callStatus.errorBuf))
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.rustPanic("Rust panic")
        }

    case CALL_CANCELLED:
        fatalError("Cancellation not supported yet")

    default:
        throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void
) {
    do {
        try writeReturn(makeCall())
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void,
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private final class UniffiHandleMap<T>: @unchecked Sendable {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

    func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        map.count
    }
}

// Public interface members begin here.

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterBool: FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return try String(bytes: readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

public protocol LarkSyncEngineProtocol: AnyObject {
    /**
     * 零落地流式导出为 TTZip（支持可选的指定子树根节点 Token）
     */
    func exportToTtzip(spaceId: String, rootNodeToken: String?, outputPath: String, cb: SyncProgressCallback) async throws

    /**
     * 异步拉取所有知识库空间
     */
    func fetchSpaces() async throws -> [WikiSpaceItem]

    /**
     * 异步拉取知识库树
     */
    func fetchWikiTree(spaceId: String) async throws -> [WikiNodeItem]

    /**
     * 将 Markdown 文本转换为 DocX Block JSON
     */
    func markdownToBlocksJson(markdown: String) throws -> String

    /**
     * 执行端到端增量同步拉取（支持可选的指定子树根节点 Token）
     */
    func syncPull(spaceId: String, rootNodeToken: String?, targetDir: String, cb: SyncProgressCallback) async throws -> UInt32
}

open class LarkSyncEngine:
    LarkSyncEngineProtocol
{
    fileprivate let pointer: UnsafeMutableRawPointer!

    // Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    public required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noPointer _: NoPointer) {
        pointer = nil
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_larksync_ffi_fn_clone_larksyncengine(self.pointer, $0) }
    }

    public convenience init(config: LarkAuthConfig, storagePath: String) throws {
        let pointer =
            try rustCallWithError(FfiConverterTypeLarkFfiError.lift) {
                uniffi_larksync_ffi_fn_constructor_larksyncengine_new(
                    FfiConverterTypeLarkAuthConfig.lower(config),
                    FfiConverterString.lower(storagePath), $0
                )
            }
        self.init(unsafeFromRawPointer: pointer)
    }

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_larksync_ffi_fn_free_larksyncengine(pointer, $0) }
    }

    /**
     * 零落地流式导出为 TTZip（支持可选的指定子树根节点 Token）
     */
    open func exportToTtzip(spaceId: String, rootNodeToken: String?, outputPath: String, cb: SyncProgressCallback) async throws {
        return
            try await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_larksync_ffi_fn_method_larksyncengine_export_to_ttzip(
                        self.uniffiClonePointer(),
                        FfiConverterString.lower(spaceId), FfiConverterOptionString.lower(rootNodeToken), FfiConverterString.lower(outputPath), FfiConverterCallbackInterfaceSyncProgressCallback.lower(cb)
                    )
                },
                pollFunc: ffi_larksync_ffi_rust_future_poll_void,
                completeFunc: ffi_larksync_ffi_rust_future_complete_void,
                freeFunc: ffi_larksync_ffi_rust_future_free_void,
                liftFunc: { $0 },
                errorHandler: FfiConverterTypeLarkFfiError.lift
            )
    }

    /**
     * 异步拉取所有知识库空间
     */
    open func fetchSpaces() async throws -> [WikiSpaceItem] {
        return
            try await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_larksync_ffi_fn_method_larksyncengine_fetch_spaces(
                        self.uniffiClonePointer()
                    )
                },
                pollFunc: ffi_larksync_ffi_rust_future_poll_rust_buffer,
                completeFunc: ffi_larksync_ffi_rust_future_complete_rust_buffer,
                freeFunc: ffi_larksync_ffi_rust_future_free_rust_buffer,
                liftFunc: FfiConverterSequenceTypeWikiSpaceItem.lift,
                errorHandler: FfiConverterTypeLarkFfiError.lift
            )
    }

    /**
     * 异步拉取知识库树
     */
    open func fetchWikiTree(spaceId: String) async throws -> [WikiNodeItem] {
        return
            try await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_larksync_ffi_fn_method_larksyncengine_fetch_wiki_tree(
                        self.uniffiClonePointer(),
                        FfiConverterString.lower(spaceId)
                    )
                },
                pollFunc: ffi_larksync_ffi_rust_future_poll_rust_buffer,
                completeFunc: ffi_larksync_ffi_rust_future_complete_rust_buffer,
                freeFunc: ffi_larksync_ffi_rust_future_free_rust_buffer,
                liftFunc: FfiConverterSequenceTypeWikiNodeItem.lift,
                errorHandler: FfiConverterTypeLarkFfiError.lift
            )
    }

    /**
     * 将 Markdown 文本转换为 DocX Block JSON
     */
    open func markdownToBlocksJson(markdown: String) throws -> String {
        return try FfiConverterString.lift(rustCallWithError(FfiConverterTypeLarkFfiError.lift) {
            uniffi_larksync_ffi_fn_method_larksyncengine_markdown_to_blocks_json(self.uniffiClonePointer(),
                                                                                 FfiConverterString.lower(markdown), $0)
        })
    }

    /**
     * 执行端到端增量同步拉取（支持可选的指定子树根节点 Token）
     */
    open func syncPull(spaceId: String, rootNodeToken: String?, targetDir: String, cb: SyncProgressCallback) async throws -> UInt32 {
        return
            try await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_larksync_ffi_fn_method_larksyncengine_sync_pull(
                        self.uniffiClonePointer(),
                        FfiConverterString.lower(spaceId), FfiConverterOptionString.lower(rootNodeToken), FfiConverterString.lower(targetDir), FfiConverterCallbackInterfaceSyncProgressCallback.lower(cb)
                    )
                },
                pollFunc: ffi_larksync_ffi_rust_future_poll_u32,
                completeFunc: ffi_larksync_ffi_rust_future_complete_u32,
                freeFunc: ffi_larksync_ffi_rust_future_free_u32,
                liftFunc: FfiConverterUInt32.lift,
                errorHandler: FfiConverterTypeLarkFfiError.lift
            )
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeLarkSyncEngine: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = LarkSyncEngine

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> LarkSyncEngine {
        return LarkSyncEngine(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: LarkSyncEngine) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LarkSyncEngine {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: LarkSyncEngine, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeLarkSyncEngine_lift(_ pointer: UnsafeMutableRawPointer) throws -> LarkSyncEngine {
    return try FfiConverterTypeLarkSyncEngine.lift(pointer)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeLarkSyncEngine_lower(_ value: LarkSyncEngine) -> UnsafeMutableRawPointer {
    return FfiConverterTypeLarkSyncEngine.lower(value)
}

public struct LarkAuthConfig {
    public var appId: String
    public var appSecret: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(appId: String, appSecret: String) {
        self.appId = appId
        self.appSecret = appSecret
    }
}

extension LarkAuthConfig: Equatable, Hashable {
    public static func == (lhs: LarkAuthConfig, rhs: LarkAuthConfig) -> Bool {
        if lhs.appId != rhs.appId {
            return false
        }
        if lhs.appSecret != rhs.appSecret {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(appId)
        hasher.combine(appSecret)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeLarkAuthConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LarkAuthConfig {
        return
            try LarkAuthConfig(
                appId: FfiConverterString.read(from: &buf),
                appSecret: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: LarkAuthConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.appId, into: &buf)
        FfiConverterString.write(value.appSecret, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeLarkAuthConfig_lift(_ buf: RustBuffer) throws -> LarkAuthConfig {
    return try FfiConverterTypeLarkAuthConfig.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeLarkAuthConfig_lower(_ value: LarkAuthConfig) -> RustBuffer {
    return FfiConverterTypeLarkAuthConfig.lower(value)
}

public struct SyncProgressEventDto {
    public var currentStep: String
    public var processedItems: UInt32
    public var totalItems: UInt32
    public var currentItemName: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(currentStep: String, processedItems: UInt32, totalItems: UInt32, currentItemName: String) {
        self.currentStep = currentStep
        self.processedItems = processedItems
        self.totalItems = totalItems
        self.currentItemName = currentItemName
    }
}

extension SyncProgressEventDto: Equatable, Hashable {
    public static func == (lhs: SyncProgressEventDto, rhs: SyncProgressEventDto) -> Bool {
        if lhs.currentStep != rhs.currentStep {
            return false
        }
        if lhs.processedItems != rhs.processedItems {
            return false
        }
        if lhs.totalItems != rhs.totalItems {
            return false
        }
        if lhs.currentItemName != rhs.currentItemName {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(currentStep)
        hasher.combine(processedItems)
        hasher.combine(totalItems)
        hasher.combine(currentItemName)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSyncProgressEventDto: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SyncProgressEventDto {
        return
            try SyncProgressEventDto(
                currentStep: FfiConverterString.read(from: &buf),
                processedItems: FfiConverterUInt32.read(from: &buf),
                totalItems: FfiConverterUInt32.read(from: &buf),
                currentItemName: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: SyncProgressEventDto, into buf: inout [UInt8]) {
        FfiConverterString.write(value.currentStep, into: &buf)
        FfiConverterUInt32.write(value.processedItems, into: &buf)
        FfiConverterUInt32.write(value.totalItems, into: &buf)
        FfiConverterString.write(value.currentItemName, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSyncProgressEventDto_lift(_ buf: RustBuffer) throws -> SyncProgressEventDto {
    return try FfiConverterTypeSyncProgressEventDto.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSyncProgressEventDto_lower(_ value: SyncProgressEventDto) -> RustBuffer {
    return FfiConverterTypeSyncProgressEventDto.lower(value)
}

public struct WikiNodeItem {
    public var nodeToken: String
    public var objToken: String
    public var objType: String
    public var parentNodeToken: String?
    public var title: String
    public var hasChild: Bool
    public var objEditTime: String?

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(nodeToken: String, objToken: String, objType: String, parentNodeToken: String?, title: String, hasChild: Bool, objEditTime: String?) {
        self.nodeToken = nodeToken
        self.objToken = objToken
        self.objType = objType
        self.parentNodeToken = parentNodeToken
        self.title = title
        self.hasChild = hasChild
        self.objEditTime = objEditTime
    }
}

extension WikiNodeItem: Equatable, Hashable {
    public static func == (lhs: WikiNodeItem, rhs: WikiNodeItem) -> Bool {
        if lhs.nodeToken != rhs.nodeToken {
            return false
        }
        if lhs.objToken != rhs.objToken {
            return false
        }
        if lhs.objType != rhs.objType {
            return false
        }
        if lhs.parentNodeToken != rhs.parentNodeToken {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.hasChild != rhs.hasChild {
            return false
        }
        if lhs.objEditTime != rhs.objEditTime {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(nodeToken)
        hasher.combine(objToken)
        hasher.combine(objType)
        hasher.combine(parentNodeToken)
        hasher.combine(title)
        hasher.combine(hasChild)
        hasher.combine(objEditTime)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeWikiNodeItem: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WikiNodeItem {
        return
            try WikiNodeItem(
                nodeToken: FfiConverterString.read(from: &buf),
                objToken: FfiConverterString.read(from: &buf),
                objType: FfiConverterString.read(from: &buf),
                parentNodeToken: FfiConverterOptionString.read(from: &buf),
                title: FfiConverterString.read(from: &buf),
                hasChild: FfiConverterBool.read(from: &buf),
                objEditTime: FfiConverterOptionString.read(from: &buf)
            )
    }

    public static func write(_ value: WikiNodeItem, into buf: inout [UInt8]) {
        FfiConverterString.write(value.nodeToken, into: &buf)
        FfiConverterString.write(value.objToken, into: &buf)
        FfiConverterString.write(value.objType, into: &buf)
        FfiConverterOptionString.write(value.parentNodeToken, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterBool.write(value.hasChild, into: &buf)
        FfiConverterOptionString.write(value.objEditTime, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeWikiNodeItem_lift(_ buf: RustBuffer) throws -> WikiNodeItem {
    return try FfiConverterTypeWikiNodeItem.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeWikiNodeItem_lower(_ value: WikiNodeItem) -> RustBuffer {
    return FfiConverterTypeWikiNodeItem.lower(value)
}

public struct WikiSpaceItem {
    public var spaceId: String
    public var name: String
    public var description: String
    public var spaceType: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(spaceId: String, name: String, description: String, spaceType: String) {
        self.spaceId = spaceId
        self.name = name
        self.description = description
        self.spaceType = spaceType
    }
}

extension WikiSpaceItem: Equatable, Hashable {
    public static func == (lhs: WikiSpaceItem, rhs: WikiSpaceItem) -> Bool {
        if lhs.spaceId != rhs.spaceId {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.description != rhs.description {
            return false
        }
        if lhs.spaceType != rhs.spaceType {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(spaceId)
        hasher.combine(name)
        hasher.combine(description)
        hasher.combine(spaceType)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeWikiSpaceItem: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WikiSpaceItem {
        return
            try WikiSpaceItem(
                spaceId: FfiConverterString.read(from: &buf),
                name: FfiConverterString.read(from: &buf),
                description: FfiConverterString.read(from: &buf),
                spaceType: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: WikiSpaceItem, into buf: inout [UInt8]) {
        FfiConverterString.write(value.spaceId, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.description, into: &buf)
        FfiConverterString.write(value.spaceType, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeWikiSpaceItem_lift(_ buf: RustBuffer) throws -> WikiSpaceItem {
    return try FfiConverterTypeWikiSpaceItem.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeWikiSpaceItem_lower(_ value: WikiSpaceItem) -> RustBuffer {
    return FfiConverterTypeWikiSpaceItem.lower(value)
}

public enum LarkFfiError {
    case ApiError(msg: String)
    case AuthError(msg: String)
    case IoError(msg: String)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeLarkFfiError: FfiConverterRustBuffer {
    typealias SwiftType = LarkFfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LarkFfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .ApiError(
                msg: FfiConverterString.read(from: &buf)
            )
        case 2: return try .AuthError(
                msg: FfiConverterString.read(from: &buf)
            )
        case 3: return try .IoError(
                msg: FfiConverterString.read(from: &buf)
            )
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: LarkFfiError, into buf: inout [UInt8]) {
        switch value {
        case let .ApiError(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)

        case let .AuthError(msg):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(msg, into: &buf)

        case let .IoError(msg):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(msg, into: &buf)
        }
    }
}

extension LarkFfiError: Equatable, Hashable {}

extension LarkFfiError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

public protocol SyncProgressCallback: AnyObject {
    func onProgress(progress: SyncProgressEventDto)

    func onLog(level: String, message: String)
}

/// Magic number for the Rust proxy to call using the same mechanism as every other method,
/// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

/// Put the implementation in a struct so we don't pollute the top-level namespace
private enum UniffiCallbackInterfaceSyncProgressCallback {
    /// Create the VTable using a series of closures.
    /// Swift automatically converts these into C callback functions.
    nonisolated(unsafe) static var vtable: UniffiVTableCallbackInterfaceSyncProgressCallback = .init(
        onProgress: { (
            uniffiHandle: UInt64,
            progress: RustBuffer,
            _: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceSyncProgressCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.onProgress(
                    progress: FfiConverterTypeSyncProgressEventDto.lift(progress)
                )
            }

            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onLog: { (
            uniffiHandle: UInt64,
            level: RustBuffer,
            message: RustBuffer,
            _: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceSyncProgressCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.onLog(
                    level: FfiConverterString.lift(level),
                    message: FfiConverterString.lift(message)
                )
            }

            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) in
            let result = try? FfiConverterCallbackInterfaceSyncProgressCallback.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface SyncProgressCallback: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitSyncProgressCallback() {
    uniffi_larksync_ffi_fn_init_callback_vtable_syncprogresscallback(&UniffiCallbackInterfaceSyncProgressCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private enum FfiConverterCallbackInterfaceSyncProgressCallback {
    nonisolated(unsafe) fileprivate static var handleMap = UniffiHandleMap<SyncProgressCallback>()
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceSyncProgressCallback: FfiConverter {
    typealias SwiftType = SyncProgressCallback
    typealias FfiType = UInt64

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeWikiNodeItem: FfiConverterRustBuffer {
    typealias SwiftType = [WikiNodeItem]

    static func write(_ value: [WikiNodeItem], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeWikiNodeItem.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [WikiNodeItem] {
        let len: Int32 = try readInt(&buf)
        var seq = [WikiNodeItem]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeWikiNodeItem.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeWikiSpaceItem: FfiConverterRustBuffer {
    typealias SwiftType = [WikiSpaceItem]

    static func write(_ value: [WikiSpaceItem], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeWikiSpaceItem.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [WikiSpaceItem] {
        let len: Int32 = try readInt(&buf)
        var seq = [WikiSpaceItem]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeWikiSpaceItem.read(from: &buf))
        }
        return seq
    }
}

private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_MAYBE_READY: Int8 = 1

private let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

private func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> Void,
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> Void,
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call uniffiEnsureInitialized() since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                uniffiFutureContinuationCallback,
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

/// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
/// lift the return value or error and resume the suspended function.
private func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}

/// Use a global variable to perform the versioning checks. Swift ensures that
/// the code inside is only computed once.
nonisolated(unsafe) private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_larksync_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if uniffi_larksync_ffi_checksum_method_larksyncengine_export_to_ttzip() != 17000 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_larksync_ffi_checksum_method_larksyncengine_fetch_spaces() != 15109 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_larksync_ffi_checksum_method_larksyncengine_fetch_wiki_tree() != 2622 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_larksync_ffi_checksum_method_larksyncengine_markdown_to_blocks_json() != 45346 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_larksync_ffi_checksum_method_larksyncengine_sync_pull() != 4284 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_larksync_ffi_checksum_constructor_larksyncengine_new() != 11362 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_larksync_ffi_checksum_method_syncprogresscallback_on_progress() != 36480 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_larksync_ffi_checksum_method_syncprogresscallback_on_log() != 47664 {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitSyncProgressCallback()
    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all

// MARK: - Swift 6 Concurrency Extensions
extension LarkSyncEngine: @unchecked Sendable {}
extension LarkAuthConfig: Sendable {}
extension WikiSpaceItem: Sendable {}
extension WikiNodeItem: Sendable {}
extension SyncProgressEventDto: Sendable {}
