# SPDX-License-Identifier: BSD-3-Clause OR Apache-2.0
#
# Copyright (c) 2026 MetastudyLine Inc. <contact@metastudyline.com>
# All rights reserved.

package(default_visibility = ["//visibility:public"])

exports_files(["Cargo.toml"])

load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "larksync_core",
    srcs = glob(["src/**/*.rs"]),
    edition = "2021",
    deps = [
        "@crates//:anyhow",
        "@crates//:blake3",
        "@crates//:governor",
        "@crates//:nonzero_ext",
        "@crates//:pulldown-cmark",
        "@crates//:reqwest",
        "@crates//:rusqlite",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:similar",
        "@crates//:slotmap",
        "@crates//:tar",
        "@crates//:thiserror",
        "@crates//:tokio",
        "@crates//:tracing",
        "@crates//:zstd",
    ],
)

rust_test(
    name = "larksync_core_test",
    crate = ":larksync_core",
)

